// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_tienda_web_odi.Data;

#nullable disable

namespace api_tienda_web_odi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804101224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_tienda_web_odi.Data.Auth.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.ArchivosMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MensajeId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MensajeId");

                    b.ToTable("ArchivosMensaje");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenProductoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProductoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioProductoSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoTransaccionProductoSnapshot")
                        .HasColumnType("int");

                    b.Property<bool>("VisibleParaComprador")
                        .HasColumnType("bit");

                    b.Property<bool>("VisibleParaVendedor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.MensajeChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emisor")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("MensajeChat");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Producto.FotosProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("FotosProducto");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Producto.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VendedorId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.ArchivosMensaje", b =>
                {
                    b.HasOne("api_tienda_web_odi.Data.Chats.MensajeChat", "Mensaje")
                        .WithMany("Archivos")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.Chat", b =>
                {
                    b.HasOne("api_tienda_web_odi.Data.Auth.Usuario", "Comprador")
                        .WithMany("ChatsComprador")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("api_tienda_web_odi.Data.Producto.Producto", "Producto")
                        .WithMany("Chats")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Comprador");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.MensajeChat", b =>
                {
                    b.HasOne("api_tienda_web_odi.Data.Chats.Chat", "Chat")
                        .WithMany("MensajeChat")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Producto.FotosProducto", b =>
                {
                    b.HasOne("api_tienda_web_odi.Data.Producto.Producto", "Producto")
                        .WithMany("FotosProducto")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Producto.Producto", b =>
                {
                    b.HasOne("api_tienda_web_odi.Data.Auth.Usuario", "Vendedor")
                        .WithMany("Productos")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Auth.Usuario", b =>
                {
                    b.Navigation("ChatsComprador");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.Chat", b =>
                {
                    b.Navigation("MensajeChat");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Chats.MensajeChat", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("api_tienda_web_odi.Data.Producto.Producto", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("FotosProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
